# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

# steps:
# - script: echo This runs in the default shell on any machine
# - bash: |
#     echo This multiline script always runs in Bash.
#     echo Even on Windows machines!
# - pwsh: |
#     Write-Host "This multiline script always runs in PowerShell Core."
#     Write-Host "Even on non-Windows machines!"

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactType: 'pipeline'
    artifactName: 'drop'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      Write-Host "##vso[build.addbuildtag]$(EnvironmentTag)"